# 継続的インテグレーション（CI）ワークフロー
# プルリクエストやプッシュ時にコード品質をチェック
name: CI

on:
    push:
        branches:
            - develop
    pull_request:
        branches:
            - main
            - develop

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            # ソースコードのチェックアウト
            - name: Checkout code
              uses: actions/checkout@v4

            # Bunの環境セットアップ
            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            # 依存関係のインストール
            - name: Install dependencies
              run: bun install

            # プロジェクトのビルド実行
            - name: Build
              run: bun run build

            # TypeScriptの型チェック
            - name: Type check
              run: bun run typecheck

            # ESLintによるコード品質チェック
            - name: Lint check
              run: bun run lint

            # Prettierによるフォーマットチェック
            - name: Format check
              run: bun run format:check

            # package.jsonとmanifest.jsonのバージョン整合性チェック
            - name: Check version consistency
              run: |
                  PACKAGE_VERSION=$(node -p "require('./package.json').version")
                  MANIFEST_VERSION=$(node -p "require('./manifest.json').version")
                  echo "package.json version: $PACKAGE_VERSION"
                  echo "manifest.json version: $MANIFEST_VERSION"
                  if [ "$PACKAGE_VERSION" != "$MANIFEST_VERSION" ]; then
                    echo "❌ Error: Version mismatch between package.json ($PACKAGE_VERSION) and manifest.json ($MANIFEST_VERSION)"
                    echo "Please ensure both files have the same version number."
                    exit 1
                  else
                    echo "✅ Version consistency check passed: $PACKAGE_VERSION"
                  fi

            # テストの実行
            - name: Run tests
              run: bun test
              env:
                  DISCORD_BOT_TOKEN: "test_token_for_ci"
                  DISCORD_GUILD_ID: "123456789012345678"
                  DISCORD_TEXT_CHANNEL_ID: "123456789012345678"
                  NODE_ENV: "test"